### ISSUE TITLE
rename density parameters in LCDM class

### ISSUE THREAD

**Issue by ntessore** [glass-dev/cosmology#1]
I am not a big fan of the density parameters `Om`, `Omz` etc. in the LCDM class.

Can we change those to `omega_m0`, `omega_k0` etc. for redshift 0, and `omega_m(z)`, `omega_k(z)` for the redshift-dependent functions?

**Comment by ntessore** [comment]
cc @arthurmloureiro @mwiet

**Comment by arthurmloureiro** [comment]
Is Omega_X = omega_X / h**2?
I asked you in person, I know it's not... but I think it can be confusing...

**Comment by ntessore** [comment]
@arthurmloureiro That's a good point. Maybe we should live with the mistakes ~we~ I made and keep the distances functions as they are, but use better names from now on?
